// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_ZSBW5wMmxY0IltXbYjy2uRCdU3jjMY',
    appId: '1:523989422193:android:69237bf69301ce8076cbd0',
    messagingSenderId: '523989422193',
    projectId: 'whatsapp-chat-app-9f978',
    storageBucket: 'whatsapp-chat-app-9f978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAULeTtQ_gLDvscjzDeXpU0vtJ1q0mXe4',
    appId: '1:523989422193:ios:9d998fb034761cf776cbd0',
    messagingSenderId: '523989422193',
    projectId: 'whatsapp-chat-app-9f978',
    storageBucket: 'whatsapp-chat-app-9f978.appspot.com',
    iosClientId: '523989422193-3vm9rdcg61lk27nq7sgfl859a3f9at6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );
}
